### ISSUE TITLE
D3 v4 support

### ISSUE THREAD

**Issue by martgnz** [martgnz/d3-snippets#4]
Need to update the snippets to D3 v4.

Ways to do it:
- Just update them.
- Add a setting to switch between v3 and v4 snippets (v4 enabled by default)
- Add a setting to switch between v3 and v4 snippets (v3 enabled by default)

I'm still using v3 so maybe I'm a little skewed. Thoughts @dephora, @luissevillano?

**Comment by dephora** [comment]
I haven't used v4 yet so I'm not sure what has changed other it going modular.

**Comment by martgnz** [comment]
The main change that concern us is that all the functions switch to a plain namespace.

So, for example, from `d3.scale.linear` we get to `d3.scaleLinear`. From `d3.geo.path` to `d3.geoPath`, etc.

**Comment by dephora** [comment]
Oh right, that is certainly an across the board gamechanger. My vote is for the setting to switch between. I'm willing to bet that v3 use still vastly outweighs v4 but it's certainly possible that many have rewritten with v4 to cut down app weight. So as for the default, it's probably a coin flip.

**Comment by LuisSevillano** [comment]
Yes, I think thats the way. Enable a `settings`panel inside `d3-snippets` package panel that allows the switch between d3 versions. In a future, new options could have a place there.

**Comment by martgnz** [comment]
I think that everyone is moving forward to v4, so I just updated the package.

There's a [v3 branch](https://github.com/martgnz/d3-snippets/tree/v3) if you need to come back, though.
