### ISSUE TITLE
Feature: Option for Double Quotes

### ISSUE THREAD

**Issue by dephora** [martgnz/d3-snippets#5]
As the title states - it would be nice to have the option of using double quotes for all snippets.

**Comment by martgnz** [comment]
Need to think about this. Maybe it could be added to the settings of the plugin, too.

**Comment by martgnz** [comment]
With code formatters as [prettier](https://github.com/prettier/prettier) this doesn't seem as urgent as it was before.

@dephora, you should take a look at it, it's pretty neat and it has a nice atom integration.
