### ISSUE TITLE
Add File Scope for TypeScript

### ISSUE THREAD

**Issue by pingshunhuangalex** [martgnz/d3-snippets#6]
Hi @martgnz 
The snippets work well in `.js` and `.babel`, but doesn't get activated in TypeScript, probably due to file scope set. I suggest including `.ts`, `.tsx`, `.jsx`. Thanks.

**Comment by martgnz** [comment]
Thanks for the suggestion, I've added the scopes in https://github.com/martgnz/d3-snippets/commit/0236ff4f8ca40570f14c85be9c423bef5d60e9e3.

Will release shortly ✨
